// Journal Finder v1 — per-journal enrichment metadata (Sushant, Session 2).
//
// This is the additive companion to the formatting rule files: the Finder needs
// indexing / open-access model / APC / review speed / subspecialty scope that a
// formatting rule file deliberately does NOT carry (kept separate so the Top-100
// registry-expansion lane stays unblocked). Nothing here modifies a rule file.
//
// SOURCING DOCTRINE (mirrors the rule files):
//   - Every non-null value is verified from the journal's own about / open-access
//     / author pages, cited in `source_urls`, and stamped with `verified_date`.
//   - Unknown ⇒ null (or [] for arrays). The UI renders "—" for a null cell.
//     We never guess indexing status, an APC number, or a scope tag.
//   - `accepts_case_reports` is DERIVED from the rule file's `article_types`
//     (not fetched) and merged in by getJournalMeta().
//
// CURRENCY RULE (Janine, 2026-07-25). `apc_usd` is populated ONLY when the
//   journal itself states a USD figure. We do NOT convert from GBP/EUR/PLN: a
//   converted number is a value no source ever published, and it goes stale
//   silently as the rate moves — exactly what verified-or-null forbids. Where a
//   journal states only a non-USD price, apc_usd stays null and the UI honestly
//   renders "—". Proposed follow-up to Sushant: add `apc_amount` + `apc_currency`
//   so those journals can carry their real, cited price.
//   (Precedent: biology-of-sport publishes "1000 EUR (4800 PLN or 1200 USD)" —
//   1200 is the journal's own USD figure, so it is recorded, not derived.)
//
// REVIEW-SPEED FORM (Janine, 2026-07-25). `review_speed` is free text and stays
//   in the publisher's own words INCLUDING the metric's name — "Submission to
//   first decision (median): 12 days", never a bare "12 days". Different
//   publishers measure different things (first decision vs. acceptance; medians
//   that include desk rejections vs. ones that don't). Normalising to a number
//   would invent a comparability the sources do not support.
//
// SJR CHANNEL (2026-07-25, Finder v2). Scimago standing is NOT hand-maintained
//   here. getJournalMeta() merges it from lib/finder/sjrData.ts, which is
//   generated by scripts/generate-sjr-data.mjs from the Session-92 Scimago pull
//   in docs/formatting-expansion/manifest.json (category 'Orthopedics and Sports
//   Medicine', sjr_year 2025). Do not add SJR values to the JOURNAL_META entries
//   below — regenerate instead. Journal Impact Factor is Clarivate-proprietary
//   and must never appear in this product.
//
// 2026-07-25 Janine live-verification pass: review_speed 2 -> 17 populated,
//   oa_model 9 -> 7 null, and one real defect corrected (biology-of-sport
//   apc_usd 0 -> 1200 — we were advertising a paid journal as free).
//   Elsevier / Sage / Wolters-Kluwer / Taylor & Francis pages are CAPTCHA- or
//   Cloudflare-blocked from every automated path tried (WebFetch AND a
//   browser-driven session), so their rows stay null by design, not by
//   oversight. See the vault note 2026-07-25 Submission Studio Data Audit.
//
// Janine spot-audits ≥10 journals' indexing / APC / case-report cells against
// live pages before the Finder section flips from shell to public
// (handoff ^handoff-janine-finder-metadata-audit).
//
// Populated by the Session-2 bounded enrichment pass. Slugs match the rule-file
// filenames (lib/formatting/journals/<slug>.json). Any slug absent here resolves
// to EMPTY (all null / []), which is the correct, honest default.

import type { ArticleType } from '@/lib/formatting/rulesSchema'
import type { JournalMeta } from './types'
import { SJR_DATA, NULL_SJR_STANDING } from './sjrData'

/** The enriched cells (everything except the values getJournalMeta derives). */
export type EnrichedMeta = Omit<JournalMeta, 'accepts_case_reports' | 'sjr'>

const EMPTY: EnrichedMeta = {
  indexing: [],
  oa_model: null,
  apc_usd: null,
  review_speed: null,
  scope_tags: [],
  source_urls: [],
  verified_date: null,
}

/**
 * slug → enriched metadata. Filled by the Session-2 enrichment pass; a missing
 * entry is a deliberate, honest "not yet verified" (resolves to EMPTY).
 */
export const JOURNAL_META: Record<string, EnrichedMeta> = {
  "acta-orthopaedica": { indexing: ["MEDLINE","PMC","Scopus","DOAJ"], oa_model: "oa", apc_usd: null, review_speed: "Desk rejections within 1-2 days; mean submission to rejection of peer-reviewed manuscripts around 2 months; mean submission to acceptance around 5 months (journal-stated)", scope_tags: ["general","basic-science"], source_urls: ["https://actaorthop.org/actao/metricsandindexing", "https://www.tandfonline.com/journals/iort20/about-this-journal", "https://actaorthop.org/actao/about"], verified_date: "2026-07-25" },
  "ajsm": { indexing: ["MEDLINE"], oa_model: null, apc_usd: null, review_speed: null, scope_tags: ["sports"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/7609541"], verified_date: "2026-07-15" },
  "aots": { indexing: ["MEDLINE"], oa_model: "oa", apc_usd: 4590, review_speed: "Submission to first decision (median): 7 days", scope_tags: ["general","trauma"], source_urls: ["https://link.springer.com/journal/402/how-to-publish-with-us", "https://link.springer.com/journal/402"], verified_date: "2026-07-25" },
  "aprm": { indexing: ["MEDLINE"], oa_model: "hybrid", apc_usd: null, review_speed: null, scope_tags: ["general"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=Annals+of+Physical+and+Rehabilitation+Medicine", "https://www.sciencedirect.com/science/journal/18770657/publish/open-access-options"], verified_date: "2026-07-15" },
  "arthroplasty": { indexing: ["PMC","Scopus","ESCI","DOAJ"], oa_model: "oa", apc_usd: 2790, review_speed: "Submission to first decision (median): 12 days", scope_tags: ["arthroplasty"], source_urls: ["https://arthroplasty.biomedcentral.com/", "https://doaj.org/toc/2524-7948", "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8787884/", "https://link.springer.com/journal/42836"], verified_date: "2026-07-25" },
  "arthroscopy": { indexing: ["MEDLINE"], oa_model: null, apc_usd: null, review_speed: null, scope_tags: ["sports"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/8506498"], verified_date: "2026-07-15" },
  "asian-spine-journal": { indexing: ["PMC","Scopus","DOAJ"], oa_model: "oa", apc_usd: 0, review_speed: null, scope_tags: ["spine"], source_urls: ["https://www.asianspinejournal.org/", "https://www.asianspinejournal.org/authors/processing_charge.php", "https://www.asianspinejournal.org/about/index.php"], verified_date: "2026-07-15" },
  "asmr": { indexing: ["PMC"], oa_model: "oa", apc_usd: 2000, review_speed: null, scope_tags: ["sports"], source_urls: ["https://www.sciencedirect.com/journal/arthroscopy-sports-medicine-and-rehabilitation", "https://www.arthroscopyjournal.org/article/S0749-8063(19)30478-5/fulltext"], verified_date: "2026-07-15" },
  "biology-of-sport": { indexing: ["MEDLINE","PMC","Scopus","DOAJ"], oa_model: "oa", apc_usd: 1200, review_speed: null, scope_tags: ["sports","basic-science"], source_urls: ["https://www.termedia.pl/Journal/Biology_of_Sport-78", "https://doaj.org/api/search/journals/Biology%20of%20Sport", "https://www.ncbi.nlm.nih.gov/nlmcatalog/8700872", "https://pmc.ncbi.nlm.nih.gov/journals/", "https://www.termedia.pl/Journal/Biology_of_Sport-78/For-authors"], verified_date: "2026-07-25" },
  "bjj": { indexing: ["MEDLINE","Scopus"], oa_model: "subscription", apc_usd: null, review_speed: null, scope_tags: ["general"], source_urls: ["https://boneandjoint.org.uk/journal/bjj", "https://en.wikipedia.org/wiki/The_Bone_%26_Joint_Journal"], verified_date: "2026-07-15" },
  "bjpt": { indexing: ["MEDLINE","PMC","Scopus"], oa_model: "oa", apc_usd: 3400, review_speed: null, scope_tags: ["general"], source_urls: ["https://www.sciencedirect.com/journal/brazilian-journal-of-physical-therapy/publish/open-access-options", "https://www.rbf-bjpt.org.br/en-acerca-revista"], verified_date: "2026-07-15" },
  "bjsm": { indexing: ["MEDLINE"], oa_model: "hybrid", apc_usd: null, review_speed: "Time to first decision: 20 days", scope_tags: ["sports"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/0432520", "https://bjsm.bmj.com/pages/about/"], verified_date: "2026-07-25" },
  "bmc-sports-science-medicine-rehab": { indexing: ["Scopus","PMC","DOAJ"], oa_model: "oa", apc_usd: null, review_speed: null, scope_tags: ["sports","general"], source_urls: ["https://bmcsportsscimedrehabil.biomedcentral.com/submission-guidelines/fees-and-funding", "https://doaj.org/toc/2052-1847", "https://www.scimagojr.com/journalsearch.php?q=21100397361&tip=sid"], verified_date: "2026-07-15" },
  "bmjosem": { indexing: ["PMC","Scopus","ESCI","DOAJ"], oa_model: "oa", apc_usd: null, review_speed: null, scope_tags: ["sports"], source_urls: ["https://doaj.org/toc/2055-7647", "https://bmjopensem.bmj.com/", "https://portal.issn.org/resource/ISSN/2055-7647"], verified_date: "2026-07-15" },
  "bone-joint-open": { indexing: ["PMC"], oa_model: "oa", apc_usd: 900, review_speed: null, scope_tags: ["general"], source_urls: ["https://boneandjoint.org.uk/journal/bjo", "https://boneandjoint.org.uk/journal/bjo/licensing", "https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=%22Bone+%26+Joint+open%22%5BTitle%5D"], verified_date: "2026-07-15" },
  "bone-joint-research": { indexing: ["PMC"], oa_model: "oa", apc_usd: null, review_speed: null, scope_tags: ["basic-science"], source_urls: ["https://boneandjoint.org.uk/journal/bjr", "https://boneandjoint.org.uk/journal/bjr/licensing", "https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=%22Bone+%26+Joint+research%22%5BTitle%5D"], verified_date: "2026-07-15" },
  "calcified-tissue-international": { indexing: ["MEDLINE"], oa_model: "hybrid", apc_usd: 3590, review_speed: "Submission to first decision (median): 5 days", scope_tags: ["basic-science"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=%22Calcified+tissue+international%22%5BTitle%5D", "https://link.springer.com/journal/223/how-to-publish-with-us", "https://link.springer.com/journal/223"], verified_date: "2026-07-25" },
  "corr": { indexing: ["Scopus"], oa_model: "hybrid", apc_usd: null, review_speed: null, scope_tags: ["general","basic-science"], source_urls: ["https://journals.lww.com/clinorthop/pages/open-access-information.aspx", "https://www.scimagojr.com/journalsearch.php?q=29603&tip=sid"], verified_date: "2026-07-15" },
  "crmm": { indexing: ["MEDLINE","PMC","Scopus"], oa_model: "hybrid", apc_usd: null, review_speed: "Submission to first decision (median): 3 days", scope_tags: ["general"], source_urls: ["https://link.springer.com/journal/12178"], verified_date: "2026-07-25" },
  "efort-open-reviews": { indexing: ["PMC","DOAJ"], oa_model: "oa", apc_usd: 1800, review_speed: "on average 13 weeks from submission to publication", scope_tags: ["general","trauma"], source_urls: ["https://eor.bioscientifica.com/", "https://en.wikipedia.org/wiki/EFORT_Open_Reviews", "https://doaj.org/toc/2058-5241"], verified_date: "2026-07-15" },
  "ejap": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: 4590, review_speed: "Submission to first decision (median): 6 days", scope_tags: ["sports","basic-science"], source_urls: ["https://link.springer.com/journal/421/how-to-publish-with-us", "https://link.springer.com/journal/421"], verified_date: "2026-07-25" },
  "ejss": { indexing: ["MEDLINE","Scopus","DOAJ"], oa_model: "oa", apc_usd: 2950, review_speed: null, scope_tags: ["sports"], source_urls: ["https://onlinelibrary.wiley.com/page/journal/15367290/homepage/open-access", "https://onlinelibrary.wiley.com/page/journal/15367290/homepage/productinformation.html", "https://doaj.org/toc/1536-7290"], verified_date: "2026-07-15" },
  "essr": { indexing: ["MEDLINE"], oa_model: "subscription", apc_usd: null, review_speed: null, scope_tags: ["sports"], source_urls: ["https://journals.lww.com/acsm-essr/Pages/default.aspx", "https://acsm.org/education-resources/journals/exercise-sport-sciences-reviews/"], verified_date: "2026-07-15" },
  "european-spine-journal": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: 4590, review_speed: "Submission to first decision (median): 10 days", scope_tags: ["spine"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=European+Spine+Journal", "https://link.springer.com/journal/586/how-to-publish-with-us", "https://en.wikipedia.org/wiki/European_Spine_Journal"], verified_date: "2026-07-25" },
  "fai": { indexing: ["MEDLINE"], oa_model: "hybrid", apc_usd: null, review_speed: null, scope_tags: ["foot-ankle"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=%22Foot+%26+ankle+international%22%5BTitle%5D", "https://journals.sagepub.com/author-instructions/fai", "https://us.sagepub.com/en-us/nam/journal/foot-ankle-international"], verified_date: "2026-07-15" },
  "global-spine-journal": { indexing: ["PMC","Scopus","DOAJ"], oa_model: "oa", apc_usd: 3200, review_speed: null, scope_tags: ["spine"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=%22Global+spine+journal%22%5BTitle%5D", "https://journals.sagepub.com/author-instructions/gsj", "https://us.sagepub.com/en-us/nam/global-spine-journal/journal203377"], verified_date: "2026-07-15" },
  "ijsnem": { indexing: ["MEDLINE","Scopus"], oa_model: null, apc_usd: null, review_speed: null, scope_tags: ["sports"], source_urls: ["https://en.wikipedia.org/wiki/International_Journal_of_Sport_Nutrition_and_Exercise_Metabolism", "https://journals.humankinetics.com/view/journals/ijsnem/ijsnem-overview.xml"], verified_date: "2026-07-15" },
  "ijspp": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: null, review_speed: null, scope_tags: ["sports"], source_urls: ["https://journals.humankinetics.com/view/journals/ijspp/ijspp-overview.xml", "https://www.ncbi.nlm.nih.gov/nlmcatalog/101276430"], verified_date: "2026-07-15" },
  "injury": { indexing: ["MEDLINE"], oa_model: null, apc_usd: null, review_speed: null, scope_tags: ["trauma"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=0020-1383%5BISSN%5D", "https://en.wikipedia.org/wiki/Injury_(journal)"], verified_date: "2026-07-15" },
  "international-orthopaedics": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: 4190, review_speed: "Submission to first decision (median): 12 days", scope_tags: ["general","basic-science"], source_urls: ["https://link.springer.com/journal/264/how-to-publish-with-us", "https://link.springer.com/journal/264/aims-and-scope"], verified_date: "2026-07-25" },
  "jaaos": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: null, review_speed: null, scope_tags: ["general"], source_urls: ["https://journals.lww.com/jaaos/pages/default.aspx", "https://www.prnewswire.com/news-releases/the-journal-of-the-american-academy-of-orthopaedic-surgeons-introduces-open-access-option-300271974.html"], verified_date: "2026-07-15" },
  "jat": { indexing: ["PMC"], oa_model: "oa", apc_usd: 0, review_speed: null, scope_tags: ["sports"], source_urls: ["https://www.nata.org/nata-now/series/journal-athletic-training", "https://meridian.allenpress.com/jat"], verified_date: "2026-07-15" },
  "jbjs": { indexing: ["MEDLINE"], oa_model: "hybrid", apc_usd: null, review_speed: null, scope_tags: ["general"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=0021-9355%5BISSN%5D", "https://www.jbjs.org/open-access-faq.php", "https://storefront.jbjs.org/products/jbjs-journals"], verified_date: "2026-07-15" },
  "jbjs-open-access": { indexing: ["MEDLINE","PMC","DOAJ"], oa_model: "oa", apc_usd: 2250, review_speed: null, scope_tags: ["general"], source_urls: ["https://journals.lww.com/jbjsoa/", "https://doaj.org/api/search/journals/JBJS%20Open%20Access", "https://www.ncbi.nlm.nih.gov/nlmcatalog/101726219"], verified_date: "2026-07-15" },
  "jbjs-reviews": { indexing: ["Scopus","ESCI"], oa_model: "subscription", apc_usd: null, review_speed: null, scope_tags: ["general"], source_urls: ["https://journalsearches.com/journal.php?title=jbjs+reviews", "https://journals.lww.com/jbjsreviews/pages/default.aspx", "https://pubmed.ncbi.nlm.nih.gov/27490395/"], verified_date: "2026-07-15" },
  "jbmr": { indexing: ["MEDLINE"], oa_model: null, apc_usd: null, review_speed: null, scope_tags: ["basic-science"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/8610640"], verified_date: "2026-07-15" },
  "jbmr-plus": { indexing: ["PMC","Scopus","ESCI","DOAJ"], oa_model: "oa", apc_usd: null, review_speed: null, scope_tags: ["basic-science","general"], source_urls: ["https://academic.oup.com/jbmrplus/pages/why-publish", "https://academic.oup.com/jbmrplus"], verified_date: "2026-07-15" },
  "jcsm": { indexing: ["MEDLINE","DOAJ"], oa_model: "oa", apc_usd: 5690, review_speed: null, scope_tags: ["basic-science"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/101552883", "https://onlinelibrary.wiley.com/page/journal/1353921906009/homepage/open-access", "https://doaj.org/toc/2190-6009"], verified_date: "2026-07-15" },
  "jeo": { indexing: ["Scopus","PMC"], oa_model: "oa", apc_usd: 1940, review_speed: null, scope_tags: ["general","basic-science"], source_urls: ["https://esskajournals.onlinelibrary.wiley.com/hub/journal/21971153/homepage/productinformation.html", "https://esskajournals.onlinelibrary.wiley.com/hub/journal/21971153/homepage/open-access"], verified_date: "2026-07-15" },
  "jhs": { indexing: ["MEDLINE","PMC","Scopus"], oa_model: "hybrid", apc_usd: null, review_speed: null, scope_tags: ["hand"], source_urls: ["https://www.assh.org/s/journal-of-hand-surgery", "https://www.elsevier.com/journals/the-journal-of-hand-surgery/0363-5023/open-access-options", "https://www.sciencedirect.com/journal/the-journal-of-hand-surgery/about/insights"], verified_date: "2026-07-15" },
  "jocr": { indexing: ["PMC","DOAJ"], oa_model: "oa", apc_usd: null, review_speed: null, scope_tags: ["general","trauma","arthroplasty","sports"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=%22Journal+of+Orthopaedic+Case+Reports%22%5BTitle%5D", "https://pmc.ncbi.nlm.nih.gov/articles/PMC5040557/", "https://pmc.ncbi.nlm.nih.gov/articles/PMC4719363/", "https://doaj.org/toc/2321-3817"], verified_date: "2026-07-15" },
  "jor-spine": { indexing: ["PMC","Scopus"], oa_model: "oa", apc_usd: null, review_speed: null, scope_tags: ["spine","basic-science"], source_urls: ["https://onlinelibrary.wiley.com/page/journal/25721143/homepage/productinformation.html", "https://onlinelibrary.wiley.com/journal/25721143"], verified_date: "2026-07-15" },
  "josr": { indexing: ["MEDLINE","PMC","Scopus","DOAJ"], oa_model: "oa", apc_usd: 2890, review_speed: "Submission to first decision (median): 4 days", scope_tags: ["general"], source_urls: ["https://en.wikipedia.org/wiki/Journal_of_Orthopaedic_Surgery_and_Research", "https://josr-online.biomedcentral.com/", "https://link.springer.com/journal/13018"], verified_date: "2026-07-25" },
  "jot": { indexing: ["MEDLINE"], oa_model: null, apc_usd: null, review_speed: null, scope_tags: ["trauma"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=%22Journal+of+Orthopaedic+Trauma%22%5BTitle%5D"], verified_date: "2026-07-15" },
  "journal-of-arthroplasty": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: 4420, review_speed: null, scope_tags: ["arthroplasty","basic-science"], source_urls: ["https://www.sciencedirect.com/journal/the-journal-of-arthroplasty", "https://www.arthroplastyjournal.org/", "https://www.ncbi.nlm.nih.gov/nlmcatalog/8703515"], verified_date: "2026-07-15" },
  "journal-of-bone-metabolism": { indexing: ["PMC","Scopus","ESCI"], oa_model: "oa", apc_usd: null, review_speed: "Submission to decision: 4 Weeks", scope_tags: ["basic-science"], source_urls: ["https://www.e-jbm.org/about/index.php", "https://www.e-jbm.org/", "https://pmc.ncbi.nlm.nih.gov/articles/PMC6416147/"], verified_date: "2026-07-15" },
  "journal-of-isakos": { indexing: ["MEDLINE","Scopus","ESCI"], oa_model: "oa", apc_usd: 2000, review_speed: null, scope_tags: ["sports","trauma"], source_urls: ["https://www.jisakos.com/", "https://isakos.com/JISAKOS/Open-Access", "https://www.elsevier.com/journals/journal-of-isakos/2059-7754/guide-for-authors", "https://www.ncbi.nlm.nih.gov/nlmcatalog/101680867"], verified_date: "2026-07-15" },
  "journal-of-orthopaedic-translation": { indexing: ["PMC","Scopus","DOAJ"], oa_model: "oa", apc_usd: 2500, review_speed: null, scope_tags: ["basic-science","general"], source_urls: ["https://www.sciencedirect.com/journal/journal-of-orthopaedic-translation", "https://doaj.org/api/search/journals/Journal%20of%20Orthopaedic%20Translation", "https://doaj.org/toc/2214-0328", "https://www.ncbi.nlm.nih.gov/nlmcatalog/101625127"], verified_date: "2026-07-15" },
  "journal-of-orthopaedics-and-traumatology": { indexing: ["MEDLINE","Scopus","PMC"], oa_model: "oa", apc_usd: 3290, review_speed: "Submission to first decision (median): 19 days", scope_tags: ["general","trauma"], source_urls: ["https://jorthoptraumatol.springeropen.com/about", "https://jorthoptraumatol.springeropen.com/submission-guidelines/fees-and-funding", "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2948123/", "https://link.springer.com/journal/10195"], verified_date: "2026-07-25" },
  "journal-of-sports-sciences": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: null, review_speed: null, scope_tags: ["sports"], source_urls: ["https://www.tandfonline.com/journals/rjsp20/about-this-journal", "https://www.tandfonline.com/journals/rjsp20"], verified_date: "2026-07-15" },
  "jpa": { indexing: ["MEDLINE"], oa_model: "oa", apc_usd: null, review_speed: null, scope_tags: [], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=%22Journal+of+Physiological+Anthropology%22%5BTitle%5D"], verified_date: "2026-07-15" },
  "jsams": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: null, review_speed: null, scope_tags: ["sports"], source_urls: ["https://www.jsams.org/", "https://en.wikipedia.org/wiki/Journal_of_Science_and_Medicine_in_Sport", "https://www.sciencedirect.com/journal/journal-of-science-and-medicine-in-sport"], verified_date: "2026-07-15" },
  "jscr": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: null, review_speed: null, scope_tags: ["sports"], source_urls: ["https://www.nsca.com/education/journals/journal-of-strength-and-conditioning-research/", "https://journals.lww.com/nsca-jscr/pages/default.aspx", "https://miar.ub.edu/issn/1064-8011"], verified_date: "2026-07-15" },
  "jses": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: 3850, review_speed: null, scope_tags: ["shoulder-elbow","arthroplasty","sports"], source_urls: ["https://www.sciencedirect.com/journal/journal-of-shoulder-and-elbow-surgery", "https://www.jshoulderelbow.org/", "https://www.ncbi.nlm.nih.gov/nlmcatalog/124795", "https://www.scopus.com/sourceid/21723"], verified_date: "2026-07-15" },
  "jshs": { indexing: ["MEDLINE","PMC","DOAJ"], oa_model: "oa", apc_usd: null, review_speed: null, scope_tags: ["sports"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/101606001", "https://doaj.org/toc/2095-2546"], verified_date: "2026-07-15" },
  "jssm": { indexing: ["MEDLINE","PMC","Scopus","DOAJ"], oa_model: "oa", apc_usd: 2950, review_speed: null, scope_tags: ["sports"], source_urls: ["https://www.jssm.org/", "https://www.jssm.org/dosya/Submisson2026.pdf"], verified_date: "2026-07-15" },
  "ksrr": { indexing: ["PMC","Scopus","DOAJ"], oa_model: "oa", apc_usd: 2990, review_speed: "Submission to first decision (median): 5 days", scope_tags: ["trauma","arthroplasty","sports"], source_urls: ["https://kneesurgrelatres.biomedcentral.com/about", "https://doaj.org/api/search/journals/Knee%20Surgery%20and%20Related%20Research", "https://doaj.org/toc/2234-2451", "https://www.ncbi.nlm.nih.gov/nlmcatalog/101575761", "https://link.springer.com/journal/43019"], verified_date: "2026-07-25" },
  "kssta": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: 4300, review_speed: null, scope_tags: ["trauma","sports","arthroplasty"], source_urls: ["https://esskajournals.onlinelibrary.wiley.com/journal/14337347", "https://esskajournals.onlinelibrary.wiley.com/hub/journal/14337347/homepage/open-access", "https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=Knee+Surgery+Sports+Traumatology+Arthroscopy", "https://www.scopus.com/sourceid/19890"], verified_date: "2026-07-15" },
  "msse": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: 3230, review_speed: null, scope_tags: ["sports"], source_urls: ["https://journals.lww.com/acsm-msse/pages/default.aspx", "https://en.wikipedia.org/wiki/Medicine_&_Science_in_Sports_&_Exercise", "https://acsm.org/education-resources/journals/medicine-science-in-sports-exercise/"], verified_date: "2026-07-15" },
  "nassj": { indexing: ["PMC","Scopus","ESCI","DOAJ"], oa_model: "oa", apc_usd: null, review_speed: null, scope_tags: ["spine"], source_urls: ["https://www.sciencedirect.com/journal/north-american-spine-society-journal-nassj/publish/open-access-options", "https://doaj.org/toc/2666-5484", "https://www.nassopenaccess.org/"], verified_date: "2026-07-15" },
  "ojsm": { indexing: ["PMC","Scopus","DOAJ"], oa_model: "oa", apc_usd: 1500, review_speed: null, scope_tags: ["sports","arthroplasty","shoulder-elbow"], source_urls: ["https://doaj.org/toc/2325-9671", "https://www.sportsmed.org/journals-podcasts/ojsm", "https://journals.sagepub.com/home/ojs"], verified_date: "2026-07-15" },
  "oscrsj": { indexing: [], oa_model: "oa", apc_usd: 399, review_speed: null, scope_tags: ["general","trauma","sports","spine","arthroplasty","pediatric","hand","foot-ankle","oncology","shoulder-elbow"], source_urls: ["https://www.oscrsj.com/aims-scope", "https://www.oscrsj.com/apc"], verified_date: "2026-08-02" },
  "osteoarthritis-cartilage": { indexing: ["MEDLINE"], oa_model: "hybrid", apc_usd: 4260, review_speed: null, scope_tags: ["basic-science"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/9305697", "https://www.sciencedirect.com/journal/osteoarthritis-and-cartilage/publish/open-access-options"], verified_date: "2026-07-15" },
  "otsr": { indexing: ["MEDLINE"], oa_model: "oa", apc_usd: 4030, review_speed: null, scope_tags: ["general","trauma"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=%22Orthopaedics+%26+traumatology%2C+surgery+%26+research%22%5BTitle%5D", "https://www.sciencedirect.com/journal/orthopaedics-and-traumatology-surgery-and-research"], verified_date: "2026-07-15" },
  "physical-therapy-in-sport": { indexing: ["MEDLINE"], oa_model: null, apc_usd: null, review_speed: null, scope_tags: ["sports"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=%22Physical+Therapy+in+Sport%22%5BTitle%5D"], verified_date: "2026-07-15" },
  "science-medicine-football": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: null, review_speed: null, scope_tags: ["sports"], source_urls: ["https://www.tandfonline.com/journals/rsmf20/about-this-journal", "https://www.tandfonline.com/journals/rsmf20", "https://www.ncbi.nlm.nih.gov/nlmcatalog/101724288"], verified_date: "2026-07-15" },
  "scj": { indexing: ["Scopus"], oa_model: "subscription", apc_usd: null, review_speed: null, scope_tags: ["sports"], source_urls: ["https://www.nsca.com/education/journals/strength-and-conditioning-journal/", "https://miar.ub.edu/issn/1524-1602"], verified_date: "2026-07-15" },
  "sjmss": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: 4550, review_speed: null, scope_tags: ["sports"], source_urls: ["https://onlinelibrary.wiley.com/journal/16000838", "https://www.wiley.com/en-us/Scandinavian+Journal+of+Medicine+&+Science+in+Sports-p-16000838"], verified_date: "2026-07-15" },
  "skeletal-muscle": { indexing: ["MEDLINE","PMC","Scopus","DOAJ"], oa_model: "oa", apc_usd: 2990, review_speed: "Submission to first decision (median): 9 days", scope_tags: ["basic-science"], source_urls: ["https://skeletalmusclejournal.biomedcentral.com/", "https://doaj.org/toc/2044-5040", "https://link.springer.com/journal/13395"], verified_date: "2026-07-25" },
  "spine": { indexing: ["MEDLINE"], oa_model: "hybrid", apc_usd: null, review_speed: null, scope_tags: ["spine"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=0362-2436%5BISSN%5D", "https://www.wolterskluwer.com/en/solutions/open-access-at-wolters-kluwer-health/lippincott-open-access/journals", "https://shop.lww.com/spine/p/0362-2436"], verified_date: "2026-07-15" },
  "sports-health": { indexing: ["MEDLINE","PMC","Scopus"], oa_model: "hybrid", apc_usd: 4400, review_speed: null, scope_tags: ["sports"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=%22Sports+health%22%5BTitle%5D", "https://journals.sagepub.com/author-instructions/sph", "https://www.sportsmed.org/journals/sports-health"], verified_date: "2026-07-15" },
  "sports-medicine": { indexing: ["MEDLINE"], oa_model: "hybrid", apc_usd: null, review_speed: "Submission to first decision (median): 31 days", scope_tags: ["sports"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/8412297", "https://link.springer.com/journal/40279"], verified_date: "2026-07-25" },
  "sports-medicine-open": { indexing: ["PMC","DOAJ"], oa_model: "oa", apc_usd: 4390, review_speed: "Submission to first decision (median): 36 days", scope_tags: ["sports"], source_urls: ["https://www.ncbi.nlm.nih.gov/nlmcatalog/?term=%22Sports+medicine+-+open%22%5BTitle%5D", "https://doaj.org/toc/2198-9761", "https://sportsmedicine-open.springeropen.com/submission-guidelines/fees-and-funding", "https://link.springer.com/journal/40798"], verified_date: "2026-07-25" },
  "tamd": { indexing: ["Scopus","DOAJ"], oa_model: "oa", apc_usd: 3000, review_speed: null, scope_tags: ["general","basic-science"], source_urls: ["https://journals.sagepub.com/home/tab", "https://us.sagepub.com/en-us/nam/journal/therapeutic-advances-musculoskeletal-disease"], verified_date: "2026-07-15" },
  "the-spine-journal": { indexing: ["MEDLINE","Scopus"], oa_model: "hybrid", apc_usd: 4880, review_speed: null, scope_tags: ["spine","basic-science"], source_urls: ["https://www.sciencedirect.com/journal/the-spine-journal", "https://www.thespinejournalonline.com/", "https://www.ncbi.nlm.nih.gov/nlmcatalog/101130732"], verified_date: "2026-07-15" },
}

/**
 * Full JournalMeta for a slug: enriched cells + derived accepts_case_reports.
 * `articleTypes` comes from the journal's rule file at the call site (server),
 * so case-report acceptance is always accurate and never fetched.
 */
export function getJournalMeta(slug: string, articleTypes: ArticleType[]): JournalMeta {
  const enriched = JOURNAL_META[slug] ?? EMPTY
  return {
    ...enriched,
    accepts_case_reports: articleTypes.includes('case_report'),
    // Generated channel, not hand-maintained — see the SJR note in the header.
    sjr: SJR_DATA[slug] ?? NULL_SJR_STANDING,
  }
}
