// DO NOT EDIT — generated by scripts/generate-sjr-data.mjs
//
// SJR standing for every registry journal, copied verbatim from the Session-92
// Scimago pull at docs/formatting-expansion/manifest.json (category
// 'Orthopedics and Sports Medicine', id 2732; 341 journals total;
// metrics based on Scopus data as of March 2026). Regenerate with
// `npm run generate:sjr` — never hand-edit this file.
//
// WHY SJR AND NOT IMPACT FACTOR. Journal Impact Factor is Clarivate-proprietary
// and may not be redistributed in this product. SJR is Scimago's freely licensed
// indicator. Do not add an IF field, ever.
//
// UNRANKED JOURNALS. A slug whose manifest row carries `rank: null` (jocr, which
// sits outside the top-100 capture, and oscrsj, which is new and unranked) gets
// an all-null standing. That is a real absence of data, not a zero: consumers
// must render it as "Not SJR-ranked" and must never sort it as if it were last
// on merit.

export interface SjrStanding {
  /** Rank within Scimago category 'Orthopedics and Sports Medicine' (341 journals). */
  categoryRank: number | null
  /** SJR score (Scimago Journal Rank indicator). */
  sjr: number | null
  quartile: 'Q1' | 'Q2' | 'Q3' | 'Q4' | null
  /** SJR data year per the manifest. */
  year: number | null
  /** Provenance: 'scimago-manifest-2026-07-12'. */
  source: string
}

export const SJR_CATEGORY = 'Orthopedics and Sports Medicine'
export const SJR_CATEGORY_SIZE = 341

/** Standing for a slug the registry knows nothing about. */
export const NULL_SJR_STANDING: SjrStanding = {
  categoryRank: null,
  sjr: null,
  quartile: null,
  year: null,
  source: 'unknown-slug',
}

export const SJR_DATA: Record<string, SjrStanding> = {
  'acta-orthopaedica': { categoryRank: 46, sjr: 1.228, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'ajsm': { categoryRank: 7, sjr: 2.29, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'aots': { categoryRank: 72, sjr: 0.952, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'aprm': { categoryRank: 35, sjr: 1.359, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'arthroplasty': { categoryRank: 24, sjr: 1.546, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'arthroscopy': { categoryRank: 8, sjr: 2.11, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'asian-spine-journal': { categoryRank: 45, sjr: 1.241, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'asmr': { categoryRank: 70, sjr: 0.956, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'biology-of-sport': { categoryRank: 11, sjr: 1.987, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'bjj': { categoryRank: 20, sjr: 1.66, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'bjpt': { categoryRank: 65, sjr: 0.996, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'bjsm': { categoryRank: 1, sjr: 4.847, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'bmc-sports-science-medicine-rehab': { categoryRank: 64, sjr: 0.999, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'bmjosem': { categoryRank: 60, sjr: 1.025, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'bone-joint-open': { categoryRank: 40, sjr: 1.273, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'bone-joint-research': { categoryRank: 33, sjr: 1.392, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'calcified-tissue-international': { categoryRank: 36, sjr: 1.312, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'corr': { categoryRank: 49, sjr: 1.183, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'crmm': { categoryRank: 22, sjr: 1.621, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'efort-open-reviews': { categoryRank: 21, sjr: 1.63, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'ejap': { categoryRank: 68, sjr: 0.985, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'ejss': { categoryRank: 54, sjr: 1.137, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'essr': { categoryRank: 27, sjr: 1.514, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'european-spine-journal': { categoryRank: 55, sjr: 1.137, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'fai': { categoryRank: 39, sjr: 1.288, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'global-spine-journal': { categoryRank: 38, sjr: 1.306, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'ijsnem': { categoryRank: 62, sjr: 1.007, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'ijspp': { categoryRank: 15, sjr: 1.833, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'injury': { categoryRank: 106, sjr: 0.773, quartile: 'Q2', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'international-orthopaedics': { categoryRank: 67, sjr: 0.987, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jaaos': { categoryRank: 50, sjr: 1.174, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jat': { categoryRank: 51, sjr: 1.166, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jbjs': { categoryRank: 31, sjr: 1.422, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jbjs-open-access': { categoryRank: 19, sjr: 1.673, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jbjs-reviews': { categoryRank: 66, sjr: 0.994, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jbmr': { categoryRank: 6, sjr: 2.423, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jbmr-plus': { categoryRank: 63, sjr: 1.007, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jcsm': { categoryRank: 4, sjr: 3.534, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jeo': { categoryRank: 71, sjr: 0.956, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jhs': { categoryRank: 57, sjr: 1.066, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jocr': { categoryRank: null, sjr: null, quartile: null, year: null, source: 'scimago-manifest-2026-07-12' },
  'jor-spine': { categoryRank: 69, sjr: 0.97, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'josr': { categoryRank: 59, sjr: 1.029, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jot': { categoryRank: 76, sjr: 0.923, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'journal-of-arthroplasty': { categoryRank: 13, sjr: 1.878, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'journal-of-bone-metabolism': { categoryRank: 73, sjr: 0.95, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'journal-of-isakos': { categoryRank: 43, sjr: 1.245, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'journal-of-orthopaedic-translation': { categoryRank: 12, sjr: 1.944, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'journal-of-orthopaedics-and-traumatology': { categoryRank: 28, sjr: 1.481, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'journal-of-sports-sciences': { categoryRank: 61, sjr: 1.018, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jpa': { categoryRank: 75, sjr: 0.925, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jsams': { categoryRank: 26, sjr: 1.52, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jscr': { categoryRank: 47, sjr: 1.217, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jses': { categoryRank: 18, sjr: 1.675, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jshs': { categoryRank: 3, sjr: 3.715, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'jssm': { categoryRank: 56, sjr: 1.075, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'ksrr': { categoryRank: 17, sjr: 1.682, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'kssta': { categoryRank: 10, sjr: 1.998, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'msse': { categoryRank: 29, sjr: 1.481, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'nassj': { categoryRank: 58, sjr: 1.04, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'ojsm': { categoryRank: 53, sjr: 1.148, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'oscrsj': { categoryRank: null, sjr: null, quartile: null, year: null, source: 'scimago-manifest-2026-07-12' },
  'osteoarthritis-cartilage': { categoryRank: 5, sjr: 2.818, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'otsr': { categoryRank: 41, sjr: 1.266, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'physical-therapy-in-sport': { categoryRank: 74, sjr: 0.947, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'science-medicine-football': { categoryRank: 14, sjr: 1.838, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'scj': { categoryRank: 52, sjr: 1.16, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'sjmss': { categoryRank: 25, sjr: 1.525, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'skeletal-muscle': { categoryRank: 23, sjr: 1.62, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'spine': { categoryRank: 32, sjr: 1.406, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'sports-health': { categoryRank: 42, sjr: 1.264, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'sports-medicine': { categoryRank: 2, sjr: 4.065, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'sports-medicine-open': { categoryRank: 9, sjr: 2.015, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'tamd': { categoryRank: 48, sjr: 1.19, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
  'the-spine-journal': { categoryRank: 16, sjr: 1.77, quartile: 'Q1', year: 2025, source: 'scimago-manifest-2026-07-12' },
}
